In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler


df = pd.read_csv("dataset/CL-dataset.csv",sep='\t',decimal=",",index_col=0)
df.head()

Imax         E    PIL       MeanD     EDate  class
0    48  5.121928  2.567  111.000000  0.848548      0
1    25  6.125617  2.567   60.333333  1.468334      0
2    24  4.310443  2.567   15.500000  0.000000      0
3    72  4.700440  2.567   77.000000  0.995727      0
4    48  5.831955  2.567   37.200000  1.494785      0

## Normalizzazione con MinMaxScalar

In [24]:
col_names = ["Imax", "E", "PIL", "MeanD", "EDate"]
features = df[col_names]

scaler = MinMaxScaler()
X = scaler.fit_transform(features.values)# Contiene i valori su cui effettuare il clustering

X_complete=df.copy()# Contiene oltre agli attributi per il clustering anche il custemerID
X_complete[col_names] = X
print(X[:5])

[[0.00979371 0.49495998 0.16767174 0.60821918 0.36663664]
 [0.00500104 0.59195195 0.16767174 0.33059361 0.63443059]
 [0.00479267 0.41654173 0.16767174 0.08493151 0.        ]
 [0.01479475 0.45422925 0.16767174 0.42191781 0.43022915]
 [0.00979371 0.56357376 0.16767174 0.20383562 0.64585952]]


In [25]:
X_complete.to_csv('dataset/CL_Normalized-dataset.csv', sep='\t', index=True, decimal=",")

In [26]:
print(X_complete)

          Imax         E       PIL     MeanD     EDate  class
0     0.009794  0.494960  0.167672  0.608219  0.366637      0
1     0.005001  0.591952  0.167672  0.330594  0.634431      0
2     0.004793  0.416542  0.167672  0.084932  0.000000      0
3     0.014795  0.454229  0.167672  0.421918  0.430229      0
4     0.009794  0.563574  0.167672  0.203836  0.645860      0
...        ...       ...       ...       ...       ...    ...
5062  0.124818  0.394994  0.167672  0.253881  0.430996      2
5063  0.004793  0.367926  0.167672  0.000000  0.000000      2
5064  0.162534  0.637743  0.198221  0.150667  0.842525      2
5065  0.007293  0.694300  0.167672  0.201342  0.486838      2
5066  0.010419  0.517591  0.167672  0.769278  0.384111      2

[5067 rows x 6 columns]
