In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, MinMaxScaler

##Da eseguire su CL1
df = pd.read_csv("dataset/CS1-dataset.csv",sep='\t',decimal=",",index_col=0)
df.head()

CustomerID     I   Iu  Imax         E    PIL          Mb       Ts  \
0    17850.0  1707   21    12  4.335643  2.567  156.860294  5333.25   
1    13047.0  1386  105    32  6.503112  2.567  356.232222  3206.09   
2    12583.0  4992  113   360  6.504979  2.752  442.969333  6644.54   
3    13748.0   439   24    80  4.494680  2.567  189.650000   948.25   
4    15100.0    80    1    32  0.000000  2.567  292.000000   876.00   

       MeanD   MaxD  MinD     EDate  
0   0.000000    0.0   0.0  0.000000  
1  35.000000   70.0   0.0  2.226424  
2  24.266667   72.0   0.0  2.235084  
3  55.400000  136.0   0.0  1.177965  
4  13.000000   32.0   0.0  0.918296

## Normalizzazione con StandardScalar (Zscore)

In [14]:


col_names = ["Imax", "E", "PIL", "Mb", "MeanD", "EDate"]
features = df[col_names]

scaler = StandardScaler()
X = scaler.fit_transform(features.values)# Contiene i valori su cui effettuare il clustering

X_complete=df.copy()# Contiene oltre agli attributi per il clustering anche il custemerID
X_complete[col_names] = X
print(X[:5])

[[-0.28529211 -0.21101002  0.11414136 -0.33429947 -0.70882417 -0.7989526 ]
 [-0.18371344  0.90077361  0.11414136 -0.08542777  0.34135838  2.17136605]
 [ 1.48217668  0.90173136  0.4664659   0.0228443   0.0193024   2.18291935]
 [ 0.06007535 -0.12943339  0.11414136 -0.29336878  0.95346479  0.77259569]
 [-0.18371344 -2.43493992  0.11414136 -0.16560748 -0.31875636  0.42616517]]


## Normalizzazione con MinMaxScalar

In [15]:
col_names = ["Imax", "E", "PIL", "Mb", "MeanD", "EDate"]
features = df[col_names]

scaler = MinMaxScaler()
X = scaler.fit_transform(features.values)# Contiene i valori su cui effettuare il clustering

X_complete=df.copy()# Contiene oltre agli attributi per il clustering anche il custemerID
X_complete[col_names] = X
print(X[:5])

[[0.00229214 0.41897698 0.16767174 0.00578416 0.         0.        ]
 [0.00645968 0.6284313  0.16767174 0.01315424 0.19178082 0.9619825 ]
 [0.07480725 0.62861174 0.17979811 0.01636061 0.13296804 0.96572421]
 [0.01646176 0.43434559 0.16767174 0.00699628 0.30356164 0.50896962]
 [0.00645968 0.         0.16767174 0.0107798  0.07123288 0.39677287]]


## Considerazioni
### MinMaxScalar
Il metodo scala in un range da 0 a 1 ma può essere sensibile agli outliers

### Standard Scaler
Si calcolano la media e la deviazione standard che sono sensibili agli outliers, non garantisce un range e se i dati in input non hanno una distribuzione gaussiana non mantiene la stessa distribuzione dei dati in output

### Tanh estimator
Alcuni link dicono che sia molto buono